[package]
name = "RPS"
version = "0.1.0"
authors = ["dallyshalla <dallyshalla@gmail.com>"]

[lib]
name = "rpslib"

[[bin]]
name = "main"
path = "src/examples/main.rs"

[[bin]]
name = "random_game"
path = "src/examples/randomgame.rs"

[dependencies]
rustc-serialize = "*"
rand = "*"
